<a href="https://colab.research.google.com/github/vaibhavbawiskar-byt/DSBDA/blob/main/DSBDA_MOCK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel("/content/Demo Marks.xlsx")

In [ ]:
df.head()

,Roll no,Name of Student,Previous Year SPPU Total Marks out of 1400,%,UT 1 Marks,%.1,50% maks of Previous Year SPPU Result,50% Marks of Unit Test 1,Total 100%,Gender
0,1,RAVAL MEET MAHESH,1131,NaN,29.0,96.666667,44.0,41.0,85.0,M
1,2,HUMBE BHAKTI RAJENDRA,1107,79.071429,29.0,96.666667,42.0,41.0,83.0,F
2,3,MARATHE SANSKRUTI JAGDISH,995,71.071429,27.0,90.000000,41.0,41.0,82.0,F
3,4,THAKARE MRUNALI VINOD,1077,76.928571,28.0,93.333333,43.0,39.0,82.0,F
4,5,BHONGALE OMKAR MADHUKAR,1064,76.000000,28.0,93.333333,42.0,38.0,80.0,M

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 10 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Roll no                                      74 non-null     int64
 1   Name of Student                              74 non-null     object
 2   Previous Year SPPU Total Marks out of  1400  74 non-null     int64
 3   %                                            71 non-null     float64
 4   UT 1 Marks                                   70 non-null     float64
 5   %.1                                          69 non-null     float64
 6   50% maks of Previous Year SPPU Result        71 non-null     float64
 7   50% Marks of Unit Test 1                     72 non-null     float64
 8   Total 100%                                   72 non-null     float64
 9   Gender                                       74 non-null     object
dtypes: float64(6), int64(2), object(2)
memory usage: 5.9+ KB

In [ ]:
display(df.describe())

,Roll no,Previous Year SPPU Total Marks out of 1400,%,UT 1 Marks,%.1,50% maks of Previous Year SPPU Result,50% Marks of Unit Test 1,Total 100%
count,74.000000,74.000000,71.000000,70.000000,69.000000,71.000000,72.000000,72.000000
mean,37.500000,951.567568,68.508048,23.714286,79.371981,34.068410,33.791667,67.386905
std,21.505813,141.310024,9.196380,4.848854,16.050119,6.517295,4.835134,9.549163
min,1.000000,542.000000,43.428571,4.000000,13.333333,0.000000,21.000000,31.000000
25%,19.250000,880.000000,63.607143,21.250000,73.333333,31.500000,31.000000,63.500000
50%,37.500000,970.000000,69.357143,24.500000,83.333333,34.607143,34.500000,68.375000
75%,55.750000,1059.750000,75.678571,27.750000,93.333333,37.732143,37.000000,73.026786
max,74.000000,1203.000000,85.928571,29.000000,96.666667,44.000000,41.000000,85.000000

In [ ]:
display(df.dtypes)

Roll no                                          int64
Name of Student                                 object
Previous Year SPPU Total Marks out of  1400      int64
%                                              float64
UT 1 Marks                                     float64
%.1                                            float64
50% maks of Previous Year SPPU Result          float64
50% Marks of Unit Test 1                       float64
Total 100%                                     float64
Gender                                          object
dtype: object

In [ ]:
print(df.columns)

Index(['Roll no', 'Name of Student',
       'Previous Year SPPU Total Marks out of  1400', '%', 'UT 1 Marks', '%.1',
       '50% maks of Previous Year SPPU Result', '50% Marks of Unit Test 1',
       'Total 100%', 'Gender '],
      dtype='object')

In [ ]:
print(df["UT 1 Marks"].mean)

<bound method Series.mean of 0     29.0
1     29.0
2     27.0
3     28.0
4     28.0
      ...
69    13.0
70     4.0
71    26.0
72    18.0
73     NaN
Name: UT 1 Marks, Length: 74, dtype: float64>

In [ ]:
print(df["Previous Year SPPU Total Marks out of  1400"].mean)

<bound method Series.mean of 0     1131
1     1107
2      995
3     1077
4     1064
      ...
69     725
70     756
71     608
72     542
73     646
Name: Previous Year SPPU Total Marks out of  1400, Length: 74, dtype: int64>

In [ ]:
df.isnull()

,Roll no,Name of Student,Previous Year SPPU Total Marks out of 1400,%,UT 1 Marks,%.1,50% maks of Previous Year SPPU Result,50% Marks of Unit Test 1,Total 100%,Gender
0,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
69,False,False,False,False,False,False,False,False,False,False
70,False,False,False,False,False,False,False,False,False,False
71,False,False,False,False,False,False,False,False,False,False
72,False,False,False,True,False,False,False,False,False,False
73,False,False,False,True,True,True,True,True,True,False

In [ ]:
df.notnull()

,Roll no,Name of Student,Previous Year SPPU Total Marks out of 1400,%,UT 1 Marks,%.1,50% maks of Previous Year SPPU Result,50% Marks of Unit Test 1,Total 100%,Gender
0,True,True,True,False,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...
69,True,True,True,True,True,True,True,True,True,True
70,True,True,True,True,True,True,True,True,True,True
71,True,True,True,True,True,True,True,True,True,True
72,True,True,True,False,True,True,True,True,True,True
73,True,True,True,False,False,False,False,False,False,True

In [ ]:
print(df.columns.tolist)

<bound method IndexOpsMixin.tolist of Index(['Roll no', 'Name of Student',
       'Previous Year SPPU Total Marks out of  1400', '%', 'UT 1 Marks', '%.1',
       '50% maks of Previous Year SPPU Result', '50% Marks of Unit Test 1',
       'Total 100%', 'Gender '],
      dtype='object')>

In [ ]:
print(df.isnull().sum())

Roll no                                        0
Name of Student                                0
Previous Year SPPU Total Marks out of  1400    0
%                                              3
UT 1 Marks                                     4
%.1                                            5
50% maks of Previous Year SPPU Result          3
50% Marks of Unit Test 1                       2
Total 100%                                     2
Gender                                         0
dtype: int64

In [ ]:
print(df.max)

<bound method DataFrame.max of     Roll no            Name of Student  \
0         1          RAVAL MEET MAHESH
1         2      HUMBE BHAKTI RAJENDRA
2         3  MARATHE SANSKRUTI JAGDISH
3         4      THAKARE MRUNALI VINOD
4         5    BHONGALE OMKAR MADHUKAR
..      ...                        ...
69       70      KUNWAR ABHIJEET SINGH
70       71             TUPE OM KISHOR
71       72       DARWEY RUDRA GUNWANT
72       73       JAGTAP HARISH YUVRAJ
73       74               ASHUTOSH RAJ

    Previous Year SPPU Total Marks out of  1400          %  UT 1 Marks  \
0                                          1131        NaN        29.0
1                                          1107  79.071429        29.0
2                                           995  71.071429        27.0
3                                          1077  76.928571        28.0
4                                          1064  76.000000        28.0
..                                          ...        ...         ...
69                                          725  51.785714        13.0
70                                          756  54.000000         4.0
71                                          608  43.428571        26.0
72                                          542        NaN        18.0
73                                          646        NaN         NaN

          %.1  50% maks of Previous Year SPPU Result  \
0   96.666667                              44.000000
1   96.666667                              42.000000
2   90.000000                              41.000000
3   93.333333                              43.000000
4   93.333333                              42.000000
..        ...                                    ...
69  43.333333                              25.892857
70  13.333333                              27.000000
71  86.666667                              21.714286
72  60.000000                               0.000000
73        NaN                                    NaN

    50% Marks of Unit Test 1  Total 100% Gender
0                       41.0   85.000000       M
1                       41.0   83.000000       F
2                       41.0   82.000000       F
3                       39.0   82.000000       F
4                       38.0   80.000000       M
..                       ...         ...     ...
69                      29.0   54.892857       F
70                      25.0   52.000000       F
71                      29.0   50.714286       F
72                      31.0   31.000000       F
73                       NaN         NaN       F

[74 rows x 10 columns]>